import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Sidebar from "@/components/Sidebar";
import PageLayout from "@/components/PageLayout";

export const metadata: Metadata = {
  title: "TaskFlow",
  description: "Generated by SpecCMS"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <main>{children}</main>
        <PageLayout />
      </body>
    </html>
  );
}
